import 'angular'
import 'angular-route'
import 'jquery'
//import 'store'
import './authentication'
import './main'
import './routes'
import './modules/user/controller'
import './modules/user/actions/addition/controller'

import 'bootstrap/dist/css/bootstrap.min.css'

import 'webpack-icons-installer/bootstrap'
import './style.scss'
import './modules/user/style.scss'

import './style'
//import './menu'

import '../pictures/exit.png'
import '../pictures/IntegrationService.jpg'
import '../pictures/logo.png'
import '../pictures/search.png'
import '../pictures/user-icon.png'
import '../pictures/logo.jpg'
import '../pictures/teacher.png'